apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      name: mariadb-dbport
      targetPort: 3306
      nodePort: 31012
  selector:
    app: mariadb
  sessionAffinity: None
  type: NodePort