apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        envFrom:
        - configMapRef:
            name: acme-challenger-env
        - secretRef:
            name: acme-challenger-sec
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mariadb-storage
      volumes:
      - name: mariadb-storage
        hostPath:
          path: /data/acme-challenger/mariadb
          type: DirectoryOrCreate
